# Generated by Django 5.2.7 on 2025-10-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('seguradora', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_seguro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moeda', models.CharField(default='BRL', max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('segurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='companies.companies')),
            ],
        ),
    ]
