# Generated by Django 5.2.7 on 2025-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apolice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='apolices_pdfs/'),
        ),
    ]
