# Generated by Django 5.2.7 on 2025-10-23 13:37

import apolicies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0002_apolice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='apolices_pdfs/', validators=[apolicies.models.validate_pdf]),
        ),
    ]
