# Generated by Django 5.2.7 on 2025-10-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0003_alter_apolice_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposSeguros',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Seguro',
                'verbose_name_plural': 'Tipos de Seguros',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='apolice',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='apolicies.tiposseguros', verbose_name='Tipo de Seguro'),
        ),
    ]
