# Generated by Django 5.2.7 on 2025-10-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0004_tiposseguros_alter_apolice_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apolice',
            options={'verbose_name': 'Apólice de Seguro', 'verbose_name_plural': 'Apólices de Seguros'},
        ),
    ]
