# Generated by Django 5.2.7 on 2025-10-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0005_alter_apolice_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apolice',
            old_name='tipo',
            new_name='tipo_seguro',
        ),
    ]
