# Generated by Django 5.2.7 on 2025-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apolicies', '0006_rename_tipo_apolice_tipo_seguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolice',
            name='observacoes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
