# Generated by Django 5.2.7 on 2025-10-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('código', models.CharField(max_length=4, unique=True)),
                ('Nome', models.CharField(max_length=255)),
            ],
        ),
    ]
