# Generated by Django 5.2.7 on 2025-10-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='código',
            new_name='codigo',
        ),
    ]
