# Generated by Django 5.2.7 on 2025-10-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_código_companies_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='Nome',
            new_name='nome',
        ),
    ]
