# Generated by Django 5.2.7 on 2025-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_nome_companies_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
