# Generated by Django 5.2.7 on 2025-10-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companies_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
